const REDUCER_KEY = 'reduxDataSSR';
const SET_LOADED_COMPONENT = 'SET_LOADED_COMPONENT';
const DISMISS_LOADED_COMPONENT = 'DISMISS_LOADED_COMPONENT';

export {
  REDUCER_KEY,
  SET_LOADED_COMPONENT,
  DISMISS_LOADED_COMPONENT,
};
